OpenConceptLab/ocl_issues#766 | API Versioning
OpenConceptLab/oclapi2 pull request #10
Opened 2021-06-01 08:06 UTC by snyaggarwal

#### Tasks:
- [x] API_VERSION env var for major.minor.maintenance
- [x] API_BUILD env var for commit SHA (default `dev`)
- [x] `core.__version__` to reflect api version (with build)
- [x] All responses to have a custom header `X-OCL-API-VERSION` (using middleware)
- [x] `/` API to show version (with build) info with other info
- [x] `/version/` API to tell app version (with build)

2021-06-04 12:07 UTC, rkorytkowski requested changes

2021-06-04 12:07 UTC, rkorytkowski commented on core/settings.py
> +API_BUILD = os.environ.get('API_BUILD', 'dev')
We don't want it to be a runtime variable rather a build time variable. In other words please hardcode version, build number and full version with build number in core/__init__.py and read it from core/settings.py. It needs to be set by a build script when running docker-compose build. I can do that part.

2021-06-05 13:50 UTC, snyaggarwal commented on core/settings.py
> +API_BUILD = os.environ.get('API_BUILD', 'dev')
Added version/build in core/__init__.py

2021-06-07 09:03 UTC, rkorytkowski approved these changes

2021-06-07 09:03 UTC, merged